%YAML 1.2
---

#I/O files

inputFile: /media/alareo/TOSHIBA EXT/GNB-Doctorado/RawData/01-Jul-2016/16h04m16s-01-Jul-2016.dat
outputFile: files/ejemploTransition.h5

#Spike Detector: Upcross, Downcross or FormSpike
spikeDetector : Upcross

#Problem execution data
volColumn: 4
totalTime: 1470
volThreshold: 6
wordLengths: [4]
binTimes: [90.0]
#wordLengths: [2,3,4,5]
#binTimes: [20.0,30.0,40.0,50.0,60.0,70.0,80.0,90.0,100.0,110.0,120.0,130.0,140.0,150.0,160.0,170.0,180.0,190.0,200.0,210.0]

...
